---
title: "360hw7"
output: html_document
date: "2024-03-21"
---

# 1

```{r}
#divorce <- read.csv("divorce(Sheet1).csv")

```



### 1c

```{r}
taub2 <- 16
tauc2 <- 16

#x <- divorce$X
#y <- divorce$Y
x <- c(2,0,0,1,0,-1,3,9,0,2,-1,1,6,0,-2,-1,4,2,0,0,3,0,3,12,-3)
y <- c(0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,0,1,1,0,0,1,0,0,1,0)

rcnorm<-function(n,mean=0,sd=1,a=-Inf,b=Inf){
  u<-runif(n, pnorm((a-mean)/sd), pnorm((b-mean)/sd) )
  mean+sd*qnorm(u)
}
```

```{r}
library(coda)
```

```{r}

S <- 100
n <- length(y)

#parameters
param <- NULL

#Z is a vector so store separate
Z <- NULL

#initialize z and c
c = 0
z = ifelse(y==1, rcnorm(n, mean=beta*x, sd=1, a=c), rcnorm(n, mean=beta*x, sd=1, b=c))

for (s in 1:S){
  
  #a and b
 # a <- (1/taub2) + sum(x*x)
  #b <- sum(x*z)
  
  varB = 1/(1/taub2) + sum(x*x)
  muB = sum(x*z)/((1/taub2) + sum(x*x))
  
  #sample beta
  beta = rnorm(1, muB, sqrt(varB))
  
  #sample z
  z = ifelse(y==1, rcnorm(n, mean=beta*x, sd=1, a=c), rcnorm(n, mean=beta*x, sd=1, b=c))
  
  #sample c
  c = rcnorm(1, mean=0, sd=sqrt(tauc2), a=max(z[y==0]), b=min(z[y==1]))
  
  #store info
  param = rbind(param, c(beta, c))
  Z = rbind(Z, z)
  
}

effectiveSize(param[,1])
effectiveSize(param[,2])
effectiveSize(Z)

```




